# docker build -t peta -f Dockerfile.peta .

FROM apache/spark:3.5.7-python3 AS builder

USER root

RUN wget -P /opt/spark/jars/ https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    wget -P /opt/spark/jars/ https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.767/aws-java-sdk-bundle-1.12.767.jar && \
    wget -P /opt/spark/jars/ https://repo1.maven.org/maven2/ch/cern/sparkmeasure/spark-measure_2.12/0.24/spark-measure_2.12-0.24.jar

RUN apt-get update && apt-get install -y --no-install-recommends pkg-config libhdf5-dev && rm -rf /var/lib/apt/lists/*

FROM apache/spark:3.5.7-python3

USER root

COPY --from=builder /opt/spark/jars/*.jar /opt/spark/jars/

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    libhdf5-dev \
    libgdal-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --prefer-binary "numpy<2" "pandas<2" && \
    pip install --prefer-binary "pyarrow<11" "boto3" "matplotlib" "tqdm>=4.67.1" && \
    pip install --prefer-binary "pyspark==3.5.7" "sparkmeasure" "fiona<1.9" "rasterio<1.3" "geopandas<0.13" && \
    pip install --prefer-binary "petastorm[all]<0.14" "s3fs==2023.12.2" && \
    pip install --prefer-binary "tensorflow<=2.17"

USER spark
